# Generated by Django 2.2.5 on 2019-09-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("survey", "0009_auto_20181211_1908")]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="editable_answers",
            field=models.BooleanField(default=True, verbose_name="Users can edit their answers afterwards"),
        )
    ]
