# Generated by Django 3.0.4 on 2020-04-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20200402_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='display_by_question',
            field=models.BooleanField(default=False, verbose_name='Display by question'),
        ),
    ]
