# Generated by Django 3.0.4 on 2020-05-08 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0013_auto_20200420_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='survey_related', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
