# Generated by Django 3.0.4 on 2020-05-09 07:15

from django.db import migrations, models
import survey.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_survey_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=survey.fields.OrderField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='need_logged_user',
            field=models.BooleanField(default=True, verbose_name='Only authenticated users can see it and answer it'),
        ),
    ]
